### ISSUE TITLE
tinylog 2.4.0-M2 and slf4j-api:2.0.0-alpha5 : Class path contains slf4j bindings targeting api versions prior to 1.8

### ISSUE THREAD

**Issue by Siedlerchr** [tinylog-org/tinylog#223]
**Describe the bug**

Have a fully modularized JPMS Gradle java project and on trying to use slf4j and tinylog together, I get the following error:

```
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions prior to 1.8.
SLF4J: Ignoring binding found at [jar:file:///Users/christophs/.gradle/caches/modules-2/files-2.1/org.tinylog/slf4j-tinylog/2.4.0-M2/1206916900881747bf825a6059031961f6f82105/slf4j-tinylog-2.4.0-M2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#ignoredBindings for an explanation.

```
**To Reproduce**
1.  
2.
3.

**Environment**

```
    implementation 'org.slf4j:slf4j-api:2.0.0-alpha5'
    implementation "org.tinylog:tinylog-api:2.4.0-M2"
    implementation "org.tinylog:slf4j-tinylog:2.4.0-M2"
```
Java version: 16

**Comment by pmwmedia** [comment]
Should be fixed by commit 42c4b8e855dd765814ec2555f1b235ff34448e85 (see #222)

**Comment by pmwmedia** [comment]
Workaround: use SLF4J 2 Alpha2 until the release of tinylog 2.4.0 (planned for next week)

**Comment by Siedlerchr** [comment]
Thanks! I will then wait for the next release!

**Comment by pmwmedia** [comment]
I have just released tinylog 2.4.0. It should work now. If not, please feel free to reopen this issue.

**Comment by Siedlerchr** [comment]
Just tested with 2.4.0 Release, and I still get the same error in JabRef. I also tried adding tinylog-impl to the dependenices, but the same issues
https://github.com/JabRef/jabref/pull/8226 

Module info:
```
    requires org.slf4j;

    requires org.tinylog.api;
    requires org.tinylog.api.slf4j;

````
./gradlew run 
```
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions prior to 1.8.
SLF4J: Ignoring binding found at [jar:file:///Users/christophs/.gradle/caches/modules-2/files-2.1/org.tinylog/slf4j-tinylog/2.4.0/25092e9cb49f538556a767616b62733406e98aea/slf4j-tinylog-2.4.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#ignoredBindings for an explanation.
````

**Comment by pmwmedia** [comment]
This is really odd. Could you provide a minimal example project that I can use for reproducing your issue?

**Comment by Siedlerchr** [comment]
I will try to come up with something.

**Comment by pmwmedia** [comment]
I found the cause for the issue and going to release a bug fix tonight.

**Comment by Siedlerchr** [comment]
Thanks a lot!

**Comment by Siedlerchr** [comment]
2.4.1 is now working!
